### PR TITLE
Adding a blurb on supported media formats

### PR DESCRIPTION
**Pull request by siduppal**

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/createcontentpage.md](https://github.com/OfficeDev/Microsoft-teams-docs/blob/siduppal-patch-mediafmt/teams/createcontentpage.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C18%5Ceddc9719-9a47-bd10-0ebb-4ef3276f7a0e%5CPullRequest%5C201708180750487639-221%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/createcontentpage.md](https://github.com/OfficeDev/Microsoft-teams-docs/blob/siduppal-patch-mediafmt/teams/createcontentpage.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C18%5Ceddc9719-9a47-bd10-0ebb-4ef3276f7a0e%5CPullRequest%5C201708180805591372-221%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/createcontentpage.md](https://github.com/OfficeDev/Microsoft-teams-docs/blob/siduppal-patch-mediafmt/teams/createcontentpage.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C18%5Ceddc9719-9a47-bd10-0ebb-4ef3276f7a0e%5CPullRequest%5C201708180806584716-221%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/createcontentpage.md](https://github.com/OfficeDev/Microsoft-teams-docs/blob/siduppal-patch-mediafmt/teams/createcontentpage.md) | :white_check_mark:Succeeded | |
[teams/prerequisites.md](https://github.com/OfficeDev/Microsoft-teams-docs/blob/siduppal-patch-mediafmt/teams/prerequisites.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C18%5Ceddc9719-9a47-bd10-0ebb-4ef3276f7a0e%5CPullRequest%5C201708180808584655-221%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by majordamage** [comment]
@siduppal: Does this list also apply to bots?

**Comment by siduppal** [comment]
@majordamage - well, we don't support audio/video cards from bots yet, so this list doesn't apply to bots yet and only applies to tabs. Will refactor the documentation when bots support audio/video cards, but this seems to be the most obvious place for it right now.

**Pull request merged**
