### PR TITLE
Linking to "yo teams" Yeoman generator

### PR DESCRIPTION
**Pull request by wictorwilen**
Added some information and links to the `generator-teams` Yeoman generator

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/code.md](https://github.com/wictorwilen/Microsoft-teams-docs/blob/yoteams/teams/code.md) | :white_check_mark:Succeeded | [View](https://msdnstage.redmond.corp.microsoft.com/en-us/Microsoft-teams/code?branch=pr-en-us-272) |
[teams/createpackage.md](https://github.com/wictorwilen/Microsoft-teams-docs/blob/yoteams/teams/createpackage.md) | :white_check_mark:Succeeded | [View](https://msdnstage.redmond.corp.microsoft.com/en-us/Microsoft-teams/createpackage?branch=pr-en-us-272) |
[teams/faq.md](https://github.com/wictorwilen/Microsoft-teams-docs/blob/yoteams/teams/faq.md) | :white_check_mark:Succeeded | [View](https://msdnstage.redmond.corp.microsoft.com/en-us/Microsoft-teams/faq?branch=pr-en-us-272) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C26%5Ceddc9719-9a47-bd10-0ebb-4ef3276f7a0e%5CPullRequest%5C201710262003486856-272%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=nYZ2JfFlJeSgHyj%2Fw85Z9DjUTeaGhmSQzGUdtG9yMds%3D&st=2017-10-26T19%3A59%3A34Z&se=2017-11-26T20%3A04%3A34Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/code.md](https://github.com/wictorwilen/Microsoft-teams-docs/blob/yoteams/teams/code.md) | :white_check_mark:Succeeded | [View](https://msdnstage.redmond.corp.microsoft.com/en-us/Microsoft-teams/code?branch=pr-en-us-272) |
[teams/createpackage.md](https://github.com/wictorwilen/Microsoft-teams-docs/blob/yoteams/teams/createpackage.md) | :white_check_mark:Succeeded | [View](https://msdnstage.redmond.corp.microsoft.com/en-us/Microsoft-teams/createpackage?branch=pr-en-us-272) |
[teams/faq.md](https://github.com/wictorwilen/Microsoft-teams-docs/blob/yoteams/teams/faq.md) | :white_check_mark:Succeeded | [View](https://msdnstage.redmond.corp.microsoft.com/en-us/Microsoft-teams/faq?branch=pr-en-us-272) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C26%5Ceddc9719-9a47-bd10-0ebb-4ef3276f7a0e%5CPullRequest%5C201710262345189420-272%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=yrmmXN28UOPleR0d6A0f5xBV2uTMpkejXlqePoPyUCo%3D&st=2017-10-26T23%3A40%3A58Z&se=2017-11-26T23%3A45%3A58Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/code.md](https://github.com/wictorwilen/Microsoft-teams-docs/blob/yoteams/teams/code.md) | :white_check_mark:Succeeded | [View](https://msdnstage.redmond.corp.microsoft.com/en-us/Microsoft-teams/code?branch=pr-en-us-272) |
[teams/createpackage.md](https://github.com/wictorwilen/Microsoft-teams-docs/blob/yoteams/teams/createpackage.md) | :white_check_mark:Succeeded | [View](https://msdnstage.redmond.corp.microsoft.com/en-us/Microsoft-teams/createpackage?branch=pr-en-us-272) |
[teams/faq.md](https://github.com/wictorwilen/Microsoft-teams-docs/blob/yoteams/teams/faq.md) | :white_check_mark:Succeeded | [View](https://msdnstage.redmond.corp.microsoft.com/en-us/Microsoft-teams/faq?branch=pr-en-us-272) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C26%5Ceddc9719-9a47-bd10-0ebb-4ef3276f7a0e%5CPullRequest%5C201710262348479270-272%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=mpNdVy%2FlNwhLGLh2HSPpA5rNmQI9wY3s2%2BisFNaqlS4%3D&st=2017-10-26T23%3A44%3A24Z&se=2017-11-26T23%3A49%3A24Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/code.md](https://github.com/wictorwilen/Microsoft-teams-docs/blob/yoteams/teams/code.md) | :white_check_mark:Succeeded | [View](https://msdnstage.redmond.corp.microsoft.com/en-us/Microsoft-teams/code?branch=pr-en-us-272) |
[teams/createpackage.md](https://github.com/wictorwilen/Microsoft-teams-docs/blob/yoteams/teams/createpackage.md) | :white_check_mark:Succeeded | [View](https://msdnstage.redmond.corp.microsoft.com/en-us/Microsoft-teams/createpackage?branch=pr-en-us-272) |
[teams/faq.md](https://github.com/wictorwilen/Microsoft-teams-docs/blob/yoteams/teams/faq.md) | :white_check_mark:Succeeded | [View](https://msdnstage.redmond.corp.microsoft.com/en-us/Microsoft-teams/faq?branch=pr-en-us-272) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C26%5Ceddc9719-9a47-bd10-0ebb-4ef3276f7a0e%5CPullRequest%5C201710262349461009-272%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Aw2mU5ZBLVR2LtZ%2FgHEDy3bK6hBnWO5UpROQODYYQJY%3D&st=2017-10-26T23%3A45%3A49Z&se=2017-11-26T23%3A50%3A49Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/code.md](https://github.com/wictorwilen/Microsoft-teams-docs/blob/yoteams/teams/code.md) | :white_check_mark:Succeeded | [View](https://msdnstage.redmond.corp.microsoft.com/en-us/Microsoft-teams/code?branch=pr-en-us-272) |
[teams/createpackage.md](https://github.com/wictorwilen/Microsoft-teams-docs/blob/yoteams/teams/createpackage.md) | :white_check_mark:Succeeded | [View](https://msdnstage.redmond.corp.microsoft.com/en-us/Microsoft-teams/createpackage?branch=pr-en-us-272) |
[teams/faq.md](https://github.com/wictorwilen/Microsoft-teams-docs/blob/yoteams/teams/faq.md) | :white_check_mark:Succeeded | [View](https://msdnstage.redmond.corp.microsoft.com/en-us/Microsoft-teams/faq?branch=pr-en-us-272) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C26%5Ceddc9719-9a47-bd10-0ebb-4ef3276f7a0e%5CPullRequest%5C201710262351379088-272%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=npgqH0cXd3680%2FC0d4WkprTZN6CmitM%2FjMf3VSQc4Tg%3D&st=2017-10-26T23%3A47%3A22Z&se=2017-11-26T23%3A52%3A22Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/code.md](https://github.com/wictorwilen/Microsoft-teams-docs/blob/yoteams/teams/code.md) | :white_check_mark:Succeeded | [View](https://msdnstage.redmond.corp.microsoft.com/en-us/Microsoft-teams/code?branch=pr-en-us-272) |
[teams/createpackage.md](https://github.com/wictorwilen/Microsoft-teams-docs/blob/yoteams/teams/createpackage.md) | :white_check_mark:Succeeded | [View](https://msdnstage.redmond.corp.microsoft.com/en-us/Microsoft-teams/createpackage?branch=pr-en-us-272) |
[teams/faq.md](https://github.com/wictorwilen/Microsoft-teams-docs/blob/yoteams/teams/faq.md) | :white_check_mark:Succeeded | [View](https://msdnstage.redmond.corp.microsoft.com/en-us/Microsoft-teams/faq?branch=pr-en-us-272) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C27%5Ceddc9719-9a47-bd10-0ebb-4ef3276f7a0e%5CPullRequest%5C201710270017127080-272%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=gRHYwx1U3pXTmwGs9BI2eoKtgiIt9LrrH0GNVaAeSe4%3D&st=2017-10-27T00%3A13%3A07Z&se=2017-11-27T00%3A18%3A07Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/code.md](https://github.com/wictorwilen/Microsoft-teams-docs/blob/yoteams/teams/code.md) | :white_check_mark:Succeeded | [View](https://msdnstage.redmond.corp.microsoft.com/en-us/Microsoft-teams/code?branch=pr-en-us-272) |
[teams/createpackage.md](https://github.com/wictorwilen/Microsoft-teams-docs/blob/yoteams/teams/createpackage.md) | :white_check_mark:Succeeded | [View](https://msdnstage.redmond.corp.microsoft.com/en-us/Microsoft-teams/createpackage?branch=pr-en-us-272) |
[teams/faq.md](https://github.com/wictorwilen/Microsoft-teams-docs/blob/yoteams/teams/faq.md) | :white_check_mark:Succeeded | [View](https://msdnstage.redmond.corp.microsoft.com/en-us/Microsoft-teams/faq?branch=pr-en-us-272) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C27%5Ceddc9719-9a47-bd10-0ebb-4ef3276f7a0e%5CPullRequest%5C201710270018003834-272%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=IXAMx%2B716WSBhy5%2BH5NYq6p1nhHInFKc%2B5Y3ebqsb5Y%3D&st=2017-10-27T00%3A13%3A54Z&se=2017-11-27T00%3A18%3A54Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/code.md](https://github.com/wictorwilen/Microsoft-teams-docs/blob/yoteams/teams/code.md) | :white_check_mark:Succeeded | [View](https://msdnstage.redmond.corp.microsoft.com/en-us/Microsoft-teams/code?branch=pr-en-us-272) |
[teams/createpackage.md](https://github.com/wictorwilen/Microsoft-teams-docs/blob/yoteams/teams/createpackage.md) | :white_check_mark:Succeeded | [View](https://msdnstage.redmond.corp.microsoft.com/en-us/Microsoft-teams/createpackage?branch=pr-en-us-272) |
[teams/faq.md](https://github.com/wictorwilen/Microsoft-teams-docs/blob/yoteams/teams/faq.md) | :white_check_mark:Succeeded | [View](https://msdnstage.redmond.corp.microsoft.com/en-us/Microsoft-teams/faq?branch=pr-en-us-272) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C27%5Ceddc9719-9a47-bd10-0ebb-4ef3276f7a0e%5CPullRequest%5C201710270019106556-272%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=9vILH3i4FG%2FAO5dzDeGLxzcwO%2BBRH0sSDG%2FuXoQz91U%3D&st=2017-10-27T00%3A14%3A54Z&se=2017-11-27T00%3A19%3A54Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by billbliss** [comment]
Yeoman generator integration complete!

**Pull request merged**
