### PR TITLE
Fix user voice links

### PR DESCRIPTION
**Pull request by richardtaylorrt**

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[CONTRIBUTING.md](https://github.com/OfficeDev/Microsoft-teams-docs/blob/ritaylor/20161108a/CONTRIBUTING.md) | :white_check_mark:Succeeded | | [Details](#user-content-CONTRIBUTING.md)
[README.md](https://github.com/OfficeDev/Microsoft-teams-docs/blob/ritaylor/20161108a/README.md) | :white_check_mark:Succeeded | | [Details](#user-content-README.md)
[teams/feedback.md](https://github.com/OfficeDev/Microsoft-teams-docs/blob/ritaylor/20161108a/teams/feedback.md) | :white_check_mark:Succeeded | | [Details](#user-content-teams/feedback.md)




For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C9%5Ceddc9719-9a47-bd10-0ebb-4ef3276f7a0e%5CPullRequest%5C201611090215521028-30%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by dfederm** [comment]
:shipit:

**Comment by saldana** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[CONTRIBUTING.md](https://github.com/OfficeDev/Microsoft-teams-docs/blob/ritaylor/20161108a/CONTRIBUTING.md) | :white_check_mark:Succeeded | | [Details](#user-content-CONTRIBUTING.md)
[README.md](https://github.com/OfficeDev/Microsoft-teams-docs/blob/ritaylor/20161108a/README.md) | :white_check_mark:Succeeded | | [Details](#user-content-README.md)
[teams/feedback.md](https://github.com/OfficeDev/Microsoft-teams-docs/blob/ritaylor/20161108a/teams/feedback.md) | :white_check_mark:Succeeded | | [Details](#user-content-teams/feedback.md)




For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C9%5Ceddc9719-9a47-bd10-0ebb-4ef3276f7a0e%5CPullRequest%5C201611091902312077-30%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[CONTRIBUTING.md](https://github.com/OfficeDev/Microsoft-teams-docs/blob/ritaylor/20161108a/CONTRIBUTING.md) | :white_check_mark:Succeeded | | [Details](#user-content-CONTRIBUTING.md)
[README.md](https://github.com/OfficeDev/Microsoft-teams-docs/blob/ritaylor/20161108a/README.md) | :white_check_mark:Succeeded | | [Details](#user-content-README.md)
[teams/feedback.md](https://github.com/OfficeDev/Microsoft-teams-docs/blob/ritaylor/20161108a/teams/feedback.md) | :white_check_mark:Succeeded | | [Details](#user-content-teams/feedback.md)




For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C9%5Ceddc9719-9a47-bd10-0ebb-4ef3276f7a0e%5CPullRequest%5C201611091919436094-30%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
