### PR TITLE
Reference the min.js file

### PR DESCRIPTION
**Pull request by dfederm**

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/createconfigpage.md](https://github.com/OfficeDev/Microsoft-teams-docs/blob/dfederm/min-js/teams/createconfigpage.md) | :white_check_mark:Succeeded | | [Details](#user-content-teams/createconfigpage.md)
[teams/jslibrary.md](https://github.com/OfficeDev/Microsoft-teams-docs/blob/dfederm/min-js/teams/jslibrary.md) | :white_check_mark:Succeeded | | [Details](#user-content-teams/jslibrary.md)
[teams/prerequisites.md](https://github.com/OfficeDev/Microsoft-teams-docs/blob/dfederm/min-js/teams/prerequisites.md) | :white_check_mark:Succeeded | | [Details](#user-content-teams/prerequisites.md)
[teams/updateremove.md](https://github.com/OfficeDev/Microsoft-teams-docs/blob/dfederm/min-js/teams/updateremove.md) | :white_check_mark:Succeeded | | [Details](#user-content-teams/updateremove.md)





For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C14%5Ceddc9719-9a47-bd10-0ebb-4ef3276f7a0e%5CPullRequest%5C201611141732085741-37%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by dfederm** [comment]
FYI, this is just to prep. The min.js file hasn't made it to prod yet, so don't merge this in until it is.

**Comment by dfederm** [comment]
Closed for now as the file hasn't actually made it to prod yet. Will reopen once it's there.

**Comment by dfederm** [comment]
Ok, the min file is now in prod.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/createconfigpage.md](https://github.com/OfficeDev/Microsoft-teams-docs/blob/dfederm/min-js/teams/createconfigpage.md) | :white_check_mark:Succeeded | | [Details](#user-content-teams/createconfigpage.md)
[teams/jslibrary.md](https://github.com/OfficeDev/Microsoft-teams-docs/blob/dfederm/min-js/teams/jslibrary.md) | :white_check_mark:Succeeded | | [Details](#user-content-teams/jslibrary.md)
[teams/prerequisites.md](https://github.com/OfficeDev/Microsoft-teams-docs/blob/dfederm/min-js/teams/prerequisites.md) | :white_check_mark:Succeeded | | [Details](#user-content-teams/prerequisites.md)
[teams/updateremove.md](https://github.com/OfficeDev/Microsoft-teams-docs/blob/dfederm/min-js/teams/updateremove.md) | :white_check_mark:Succeeded | | [Details](#user-content-teams/updateremove.md)





For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C16%5Ceddc9719-9a47-bd10-0ebb-4ef3276f7a0e%5CPullRequest%5C201611161824479309-37%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
