### PR TITLE
Typo Fix

### PR DESCRIPTION
**Pull request by kushanlahiruperera**
Typo fix in 19th line.

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/design.md](https://github.com/kushanlahiruperera/Microsoft-teams-docs/blob/patch-2/teams/design.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C9%5C21%5Ceddc9719-9a47-bd10-0ebb-4ef3276f7a0e%5CPullRequest%5C201709211423264351-252%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=cTkDsRToRPfitYqNn%2FrKO52eJJJxOWpp48DiBfuL7nE%3D&st=2017-09-21T14%3A19%3A00Z&se=2017-09-22T14%3A29%3A00Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/design.md](https://github.com/kushanlahiruperera/Microsoft-teams-docs/blob/patch-2/teams/design.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C9%5C21%5Ceddc9719-9a47-bd10-0ebb-4ef3276f7a0e%5CPullRequest%5C201709211427027676-252%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=8CxvRhqFqWsqiH%2BdMQpIdgvyCuEjIqe%2FWGz2yEhN85U%3D&st=2017-09-21T14%3A22%3A39Z&se=2017-09-22T14%3A32%3A39Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kushanlahiruperera** [comment]
Pending merging of documentation fix.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/design.md](https://github.com/kushanlahiruperera/Microsoft-teams-docs/blob/patch-2/teams/design.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C9%5C21%5Ceddc9719-9a47-bd10-0ebb-4ef3276f7a0e%5CPullRequest%5C201709211835295199-252%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=%2FhXCevhsVv7N%2FC%2FdqRD1HrZSQ9gd2pBIgGUr5wb1e20%3D&st=2017-09-21T18%3A31%3A04Z&se=2017-09-22T18%3A41%3A04Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by majordamage** [comment]
Thanks for bringing this to our attention! The phrase "in situ" isn't a typo, but it also doesn't comply with the Microsoft Manual of Style for Technical Publications (MSTP), which recommends avoidance of Latin phrases. I replaced the phrase with the English equivalent.

**Pull request merged**
